/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serialportapi_usbserial_api_USBSerial */

#ifndef _Included_com_serialportapi_usbserial_api_USBSerial
#define _Included_com_serialportapi_usbserial_api_USBSerial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serialportapi_usbserial_api_USBSerial
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_serialportapi_usbserial_1api_USBSerial_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_serialportapi_usbserial_api_USBSerial
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_serialportapi_usbserial_1api_USBSerial_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
